version: '8.3'

services:
  app-dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  app-prod:
    build: .
    ports: 
      - "8001:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", '--port', "8000"]