[project]
name = "cli-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "pydantic>=2.11.7",
]
